/* Host-side generator for the pattern databases used by my_solver.c.
 *
 * Each table is a breadth-first search from solved over a relaxed problem:
 * the orientation table ignores where cubies are, the permutation table
 * ignores how they are twisted. The result is written as C arrays to stdout:
 *
 *     ./pdb_generator > pdb.h
 *
 * Statistics (entries, max, distribution) go to stderr.
 */
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "cube.h"

enum {
    ORIENT_SIZE = 729,  /* 3^6 */
    PERM_SIZE = 5040,   /* 7! */
    UNSEEN = 0xFF,
};

/* Inverse of rank_orient, with cubies left in their home positions. */
static state_t unrank_orient(uint16_t rank)
{
    state_t state;
    uint8_t sum = 0;
    for (int i = CUBIES - 2; i >= 0; --i) {
        state.o[i] = (uint8_t) (rank % 3U);
        rank = (uint16_t) (rank / 3U);
        sum = (uint8_t) (sum + state.o[i]);
    }
    state.o[CUBIES - 1] = (uint8_t) ((3U - sum % 3U) % 3U);
    for (uint8_t i = 0; i < CUBIES; ++i)
        state.p[i] = i;
    return state;
}

/* Inverse of rank_perm, with every cubie untwisted. */
static state_t unrank_perm(uint16_t rank)
{
    state_t state;
    uint8_t digit[CUBIES], used[CUBIES] = {0};
    for (int i = CUBIES - 1; i >= 0; --i) {
        digit[i] = (uint8_t) (rank % (CUBIES - i));
        rank = (uint16_t) (rank / (CUBIES - i));
    }
    for (uint8_t i = 0; i < CUBIES; ++i) {
        /* Take the digit[i]-th smallest value not used yet. */
        uint8_t k = digit[i], v;
        for (v = 0;; ++v) {
            if (used[v])
                continue;
            if (k == 0)
                break;
            --k;
        }
        used[v] = 1;
        state.p[i] = v;
        state.o[i] = 0;
    }
    return state;
}

/* BFS over `size` abstract states. unrank builds a representative full state,
 * rank projects a full state back, so a move on the representative gives the
 * same abstract neighbour whichever representative is chosen.
 */
static void build(uint8_t *table, uint16_t size, state_t (*unrank)(uint16_t),
                  uint16_t (*rank)(const state_t *))
{
    static uint16_t queue[PERM_SIZE];
    uint16_t head = 0, tail = 0;

    memset(table, UNSEEN, size);
    table[0] = 0;
    queue[tail++] = 0;
    while (head < tail) {
        uint16_t cur = queue[head++];
        state_t state = unrank(cur);
        for (uint8_t move = 0; move < MOVES; ++move) {
            state_t child = apply_move(state, move);
            uint16_t idx = rank(&child);
            if (table[idx] == UNSEEN) {
                table[idx] = (uint8_t) (table[cur] + 1);
                queue[tail++] = idx;
            }
        }
    }
}

static int report(const char *name, const uint8_t *table, uint16_t size)
{
    unsigned count[16] = {0};
    uint8_t max = 0;
    unsigned long sum = 0;
    for (uint16_t i = 0; i < size; ++i) {
        if (table[i] == UNSEEN) {
            fprintf(stderr, "%s: entry %u unreachable\n", name, i);
            return 0;
        }
        ++count[table[i]];
        sum += table[i];
        if (table[i] > max)
            max = table[i];
    }
    fprintf(stderr, "%s: %u entries, max %u, mean %.3f\n", name, size, max,
            (double) sum / size);
    for (uint8_t d = 0; d <= max; ++d)
        fprintf(stderr, "  h=%u: %u\n", d, count[d]);
    return 1;
}

static void emit(const char *name, const uint8_t *table, uint16_t size)
{
    printf("static const uint8_t %s[%u] = {", name, size);
    for (uint16_t i = 0; i < size; ++i)
        printf("%s%u,", i % 24 ? " " : "\n    ", table[i]);
    printf("\n};\n");
}

int main(void)
{
    static uint8_t orient[ORIENT_SIZE], perm[PERM_SIZE];

    build(orient, ORIENT_SIZE, unrank_orient, rank_orient);
    build(perm, PERM_SIZE, unrank_perm, rank_perm);
    if (!report("pdb_orient", orient, ORIENT_SIZE) ||
        !report("pdb_perm", perm, PERM_SIZE))
        return 1;

    printf("/* Generated by pdb_generator.c. Do not edit. */\n");
    printf("#ifndef PDB_H\n#define PDB_H\n\n#include <stdint.h>\n\n");
    emit("pdb_orient", orient, ORIENT_SIZE);
    printf("\n");
    emit("pdb_perm", perm, PERM_SIZE);
    printf("\n#endif /* PDB_H */\n");
    return 0;
}
